### ISSUE TITLE
Bugs with acrylic, modular design + request

### ISSUE THREAD

**Issue by Undisputed00x** [FeoreV/Themes#4]
First of all after using numerous famous discord themes this is becoming my fav one. I always was seeking a theme with big range of customization that can also have transparent/acrylic background and it uses outlines in theme elements for sweet contrast, some themes could do only the first, others only the second one. (im a fan of Fluent/Material UIs)

1. Im using Vencord with enabled transparency and MFE, i could get acrylic bg with default subtheme but making bg colors rgba with 0% opacity, when doing that there was a bug with acrylic on menus and tooltips like in my screenshots:
![Screenshot 2023-11-10 024638](https://github.com/FeoreV/Themes/assets/80290008/b71f8139-a89b-40cf-85a4-6ba57b9d282b)
![Screenshot 2023-11-10 024555](https://github.com/FeoreV/Themes/assets/80290008/83cc5fd3-49fc-4a99-9d5e-e403114cc389)

This issue occurs only when transparent background is present, also some time ago i was using this https://github.com/llsc12/discord-acrylic and had the same issue.
If i am using mica subtheme there wasnt any blur on menus at all.

2.  Including ModularDesign does not work at all
3.  Changing color on MaterialYou does nothing

I would like to see if possible some more color options like for disabled groups, not selected team tabs and an option to change the fonts.

**Comment by FeoreV** [comment]
Nice to hear it.

Default is not intended for use with mica. If you understand how it works, then at best you can experiment with lite.

To be honest, I don’t really understand what the modes do in mica. I put different ones, but the result was the same. I doubt this is a theme issue. If you managed to somehow change the miki mode (acrylic/tabbled/...), then please let me know.

In mica it is impossible to blur the background of discord elements. Instead of blur there will be a strange glow. OR elements OR transparent background. Add these settings to the theme file (after imports). You can try to customize it for yourself.
```
/*Mica*/
:root{
--BGopacity: 30%;
--BGcolor: var(--color2); /*color in RGB (example: 255,0,0)*/
}
```

About modulardesign. Restart discord.

About materialyou. Indeed, there are some elements that do not fit into the color scheme. I'll fix it a little later.

There will be fonts, but I don’t know how soon. If you want, you can suggest an interesting font.
I don't understand about the tabs.

If you find other errors, write (github issues/dsserver/dm)

**Comment by Undisputed00x** [comment]
2. Fixed
![Screenshot 2023-11-10 133949](https://github.com/FeoreV/Themes/assets/80290008/7d87550e-67b3-4294-93b9-9571d6a6140f)

As for fonts i prefer Segoe UI if possible
